services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
#  keycloak:
#    image: quay.io/keycloak/keycloak:25.0.1
#    container_name: keycloak
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - 8181:8080
#    command: start-dev


networks:
  postgres:
    driver: bridge

volumes:
  postgres: