spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: product-service
        uri: lb:http://product-service
        predicates[0]: Path=/api/product
      routes[1]:
        id: order-service
        uri: lb:http://order-service
        predicates[0]: Path=/api/order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
server:
  port: 8181