spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://adminUser:password@localhost:27017/product-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 0